# Site settings
title: Win with GANT & Secret Escapes
client:
  name: GANT
  link: "#client-name"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  To celebrate spring, GANT are offering you the chance to update your wardrobe with a £500 gift card plus a five star, stylish London stay. Win a two-night break in fashionable Knightsbridge and enjoy the opulent service of the Jumeirah Carlton Tower.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/gant-competition" # the subpath of your site, e.g. /blog/
img:     "/gant-competition/_assets/img"
css:     "/gant-competition/_assets/css"
js:      "/gant-competition/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed